export const symptoms_2 = [
    {
      "Description": "Some people think that depression is insignificant and not a real heath condition. This is wrong because depression is a genuine disease with real symptoms. It is not a sign of weakness or a minor thing to deal with. Rather, it is a persistent feeling of worthlessness and a lack of desire to engage in activities that were formerly pleasurable. However, with the appropriate support and treatment, most people with depression can recover completely.",
      "DescriptionShort": "Depression is the most common psychological disease in our society and is a state of hopelessness and joylessness. It is more than simply feeling hopeless or fed up for a few days. Depression is a persistent feeling of sadness for weeks or months. It can be diagnosed and treated by a specialist.",
      "MedicalCondition": "Depression is a common clinical picture and affects women twice as much as it does men. More than 3% of the population receives psychiatric treatment for depression. Possible symptoms are inhibited drive, inhibited thoughts, loss of ability to feel joy or sadness, internal unrest, sleeping disorders, morning lows, fear of the future, loss of appetite, loss of weight or weight gain, and loss of sexual drive (loss of libido).",
      "Name": "Depression",
      "PossibleSymptoms": ['Aggressiveness', 'Anxiety', 'Cravings', 'Difficulty to concentrate', 'Forgetfulness', 'Hallucination', 'Headache', 'Impairment of male potency', 'Increased appetite', 'Joylessness', 'Mood swings', 'Neck pain', 'Nervousness', 'Overweight', 'Physical inactivity', 'Reduced appetite', 'Sadness', 'Sensitivity to cold', 'Sleeplessness', 'Tiredness', 'Underweight', 'Weight gain', 'Weight loss'],
      "ProfName": "Major depressive disorder",
      "Synonyms": null,
      "TreatmentDescription": "If depression goes untreated, in the worst case it may lead to a suicide attempt. If the above symptoms are observed, a specialist should be sought for help by all means. A specialist can offer a diagnosis based on a conversation with the patient. Depression can be successfully treated with medication or psychotherapy."
    },
    {
      "Description": "Anorexia, also called anorexia nervosa, is a psychological disease in which affected persons suffer from a disturbed body perception. This causes them to feel much too overweight and unattractive and to suffer from it. They will then try to counter this perception with various measures. Those can range from strict monitoring of food intake to a complete refusal to eat. People who are affected by anorexia avoid eating sufficient quantities of food and attempt to speed up their loss of weight by vomiting, misuse of laxatives or diuretics, and excessive athletic activity. The reason for this is their warped perception of their figure. As a result of these actions, the body weight is reduced to a body mass index value under 17.5. The body mass index (BMI) is calculated by dividing the body’s weight (in kilograms, Kg) with the square of the body’s height (in meters). The BMI for a person of normal weight is 20-25. In contrast to people with anorexia, people with only bulimia (see the article on bulimia) have a BMI value over 17.5.",
      "DescriptionShort": "People with anorexia suffer from a misperception of their own body. These are mainly young women. Even though they are much too thin, they perceive themselves as “too fat” and unattractive. \nAnorexia is characterized by a severe restriction of nutrition and an intentionally induced underweight state with the patients trying to lose even more weight.",
      "MedicalCondition": "Women are affected most often, but not exclusively. As mentioned above, patients’ symptomatology or behaviour often begins with monitoring their food intake with calorie charts. This is then often followed by measures to significantly reduce weight, including excessive exercise, vomiting, laxatives, but also consumption of appetite suppressants as well as foregoing many foods. Affected persons do not like to eat in company anymore and will take a very long time to eat even smallest amounts of food.",
      "Name": "Anorexia",
      "PossibleSymptoms": ['Abdominal guarding', 'Brittleness of nails', 'Difficult defecation', 'Dry skin', 'Impairment of male potency', 'Menstruation disorder', 'Missed period', 'Nausea', 'Pallor', 'Sensitivity to cold', 'Underweight', 'Vomiting', 'Weight loss'],
      "ProfName": "Anorexia nervosa",
      "Synonyms": null,
      "TreatmentDescription": "The insufficient supply with calories, but more importantly with vitamins and other essential nutrition can cause serious or even life-threatening physical symptoms. A low body weight can lead to hormonal disorders, such as irregularity or absence of menstruation. Men with anorexia may experience loss of potency and sexual drive. When the body fails to receive sufficient nutrition, bones can no longer rebuild themselves, which can lead to the early development of chronic osteoporosis. In rare cases it can lead to a reduced heart rate and body temperature, which requires an urgent trip to the hospital. Treatment of anorexia requires a specialist and is extremely important, as undernourishment can be fatal under certain circumstances. Treatment often occurs over a long period of time and relapse is common. In the event of acute life-threatening weight loss, induced nutrition, e.g. via a gastric tube or high-calorie drinks will be the initial treatment, followed by intensive psychotherapy and nutritional counselling."
    },
    {
      "Description": "Patients with bulimia suffer from binge eating, when they “can’t stop eating until everything is gone”, followed by feelings of guilt. Being afraid of weight gain, they will initially induce vomiting using their fingers; later on the vomiting will be reflective. Patients often have a pathological fear of gaining weight. People with bulimia often maintain a normal or slightly reduced weight above a body mass index value of 17.5. Body mass index (BMI) can be calculated by dividing body weight (kg) by body height squared. A normal weight is 20-25. In contrast to bulimia, people with anorexia (see the article on anorexia) have a BMI value under 17.5.",
      "DescriptionShort": "Bulimia nervosa is a psychological disease that predominantly affects young women and shows a disturbed relationship with food intake. Affected people suffer from binge eating followed by vomiting. Instead of vomiting after binge eating, some patients might also misuse laxatives, do excessive exercise, or fast.",
      "MedicalCondition": "Even though patients suffering from bulimia nervosa are often of normal weight, unlike those suffering from anorexia nervosa, they still show strong symptoms of malnutrition. Frequent vomiting leads to bad teeth, with tooth decay and other defects, and they also suffer from stomach complaints and heartburn. Malnutrition leads to problems with the bone metabolism and to reduced performance capacity.",
      "Name": "Bulimia",
      "PossibleSymptoms": ['Anxiety', 'Brittleness of nails', 'Cough', 'Cravings', 'Dry mouth', 'Heartburn', 'Menstruation disorder', 'Missed period', 'Mood swings', 'Mouth ulcers', 'Vomiting', 'Weight gain', 'Weight loss'],
      "ProfName": "Bulimia nervosa",
      "Synonyms": null,
      "TreatmentDescription": "Even if the affected person is not extremely underweight compared to anorexia nervosa, life-threatening disruptions, especially of blood salts can occur and need to be treated immediately. The long-term treatment should aim at building an almost normal relationship with food, body weight and body perception, by applying psychotherapy and other supporting therapies (e.g. ergo therapy). Treatment will be handled by a specialist."
    },
    {
      "Description": "Sleep apnea, also called obstructive sleep apnea syndrome, is one of sleep disorders (see the article on sleep disorders) and is characterized by a cessation of breathing (apnea) that lasts 10 seconds or longer during sleep. It causes the affected person to have a daily fatigue and a tendency to fall asleep during the day.",
      "DescriptionShort": "Sleep apnea is a frequent condition in which the patient’s breathing stops from time to time while sleeping. The patient’s breathing can become shallow and these breathing pauses can last a short moment before the return of normal breathing. The condition is typically chronic.",
      "MedicalCondition": "Men and overweighted people are more frequently affected. The disorder begins with nightly snoring, and later escalates into increasingly more frequent breaks in breathing. This causes the patient to sleep poorly and the following day they are tired, sleep, and complain of morning headaches. Many also develop high blood pressure.",
      "Name": "Sleep apnea",
      "PossibleSymptoms": ['Difficulty to concentrate', 'Dry mouth', 'Forgetfulness', 'Headache', 'Impairment of male potency', 'Joylessness', 'Mood swings', 'Reduced appetite', 'Sadness', 'Sleepiness with spontaneous falling asleep', 'Tiredness'],
      "ProfName": "Sleep apnea syndrome",
      "Synonyms": "Sleep apnoea",
      "TreatmentDescription": "If sleep apnea goes on untreated, it can develop into high blood pressure, as mentioned above. Additionally, lack of concentration can be a result of feeling sleepy during the day, which increases the risk of an accident, such as a traffic accident. Patients are advised to avoid alcohol and smoking, as well as to reduce any excessive weight. A targeted treatment such as CPAP breathing therapy can be pursued. CPAP stands for “continuous positive airway pressure”. The point of this therapy is to keep the airway open and prevent cessation of breathing with the use of a CPAP breathing device, which has a closed mask that continually supplies a slight increase in pressure through the nose or mouth during sleep."
    },
    {
      "Description": "The word dementia describes a set of symptoms that can encompass difficulties with language, with problem-solving, with thinking and last but not least with memory loss. Dementia is often referred imprecisely to as “senile dementia” or “senility”, which reflects the not precise but widespread belief that severe mental failure is a normal part of aging.",
      "DescriptionShort": "Dementia is not a specific disease. It is an overall term that describes a large range of symptoms connected with a decline of thinking skills such as memory. This decline is enough severe to reduce the ability of the patient to perform everyday activities.",
      "MedicalCondition": "Dementia is caused by damage to brain cells and this damage makes the communication between brain cells less effective. This can affect feelings, thinking, and behavior. Alzheimer’s disease is the most common cause of dementia. Symptoms of dementia can vary largely. The disease affects visual perception, judgment and reasoning, ability to pay attention and focus, language and communication, and memory. People with the condition may have issues with short-term memory, planning and cooking meals, paying bills, keeping track of a wallet or purse, remembering neighbors or the neighborhood or remembering appointments. Many dementias are progressive. This means that symptoms begin slowly and get worse gradually.",
      "Name": "Senility",
      "PossibleSymptoms": ['Aggressiveness', 'Agitation', 'Anxiety', 'Difficulty in finding words', 'Difficulty in speaking', 'Disorientation regarding time or place', 'Forgetfulness', 'Immobilization', 'Memory gap', 'Sleeplessness'],
      "ProfName": "Dementia",
      "Synonyms": null,
      "TreatmentDescription": "Treatment of dementia depends on its cause. For progressive dementias, there is no treatment and no cure that stops or slows its progression. However, there is medication that may improve symptoms temporarily. If a loved one is experiencing some memory troubles or issues in thinking skills, it should be taken seriously. The affected person should visit immediately a doctor to investigate these. A professional assessment can detect a condition that can be treatable. An early diagnosis of dementia can allow the patient to benefit greatly from available treatments and it offers time to plan for the future."
    },
    {
      "Description": "Two basic types of anxiety disorder are recognized. The first is a kind of situation-specific anxiety disorder (phobia) that is triggered by defined situations or objects (such as arachnophobia or agoraphobia). The second is a situation-unspecific anxiety disorder that includes panic attack and general anxiety disorders. Panic attacks are short term, suddenly set in, and are accompanied by fears related to the body (such as dying or suffocating) and by pronounced physical difficulties. Generalized anxiety attacks are characterized by lasting several months, associated with stress, worry, and fear.",
      "DescriptionShort": "An anxiety disorder is a psychological disorder in which the affected individual experiences anxiety due to unspecified triggers, certain circumstances, or situations which limit his everyday capabilities.",
      "MedicalCondition": "Anxiety disorders are among the most common psychological disorders. The chances of experiencing an anxiety disorder at some point in life are 10-15%. Women are twice as likely to suffer from anxiety disorders. Anxiety disorders are often accompanied by depression and abuse of medication. People with anxiety disorders suffer from anxiety coupled with physical ailments. These may include heart palpitations, shortness of breath, dizziness, being dazed, hot flashes, chills, dry mouth, tremors, and crawling sensations on the skin. Long term anxiety disorder can lead to avoidance behaviors like running away or social withdrawal.",
      "Name": "Excessive feeling of fear",
      "PossibleSymptoms": ['Agitation', 'Anxiety', 'Breathing-related pains', 'Chest pain', 'Chest tightness', 'Cold sweats', 'Deepened breathing', 'Diarrhea', 'Dizziness', 'Drowsiness', 'Fast', 'Feeling faint', 'Hot flushes', 'Irregular heartbeat', 'Itching of skin', 'Joylessness', 'Memory gap', 'Neck pain', 'Nervousness', 'Night sweats', 'Palpitations', 'Sadness', 'Shortness of breath', 'Sleeplessness', 'Sweating', 'Tremor at rest'],
      "ProfName": "Anxiety disorder",
      "Synonyms": "Panic disorder,Panic attacks",
      "TreatmentDescription": "Anxiety disorders can be treated  relatively well with pscicological therapy. Anti-depression treatment may also be pursued to support other efforts. It’s common for a panic attack to spontaneously occur and disappear. In between, the patient should seek psychotherapeutic help and antidepressants if necessary. The same applies for general anxiety disorders."
    },
    {
      "Description": "Chronic fatigue syndrome causes persistent fatigue or exhaustion that affects everyday life causing limitations in a patient’s activity. It is a serious condition that can cause long-term disability and illness. However the health condition of many people, especially young people and children, improves over time. The chronic tiredness doesn't get better with rest. It can even get worse with physical or mental activity. The symptoms of the condition may also arise from multiple underlying health issues.",
      "DescriptionShort": "Chronic fatigue syndrome is a disease, as the name says, which is distinguished by chronic tiredness, causing limitations in a patient’s activity over a long period of time. The peculiarity of this extreme tiredness is that there is no other underlying disease which can be taken as an explanation for it.",
      "MedicalCondition": "According to the Center for Disease Control, chronic fatigue syndrome presents the following symptoms:  newly occurring states of exhaustion that last longer than 6 months. They can not be connected to any type of stress and they do not improve after taking a rest. The state of exhaustion leads to limited activity. It can also lead to painful lymph nodes, muscle aches, joint pain, and headaches. Many patients report trouble of thinking, sleep that isn’t revigorating, and chronic general feelings of illness after strenuous activity.",
      "Name": "Chronic tiredness syndrome",
      "PossibleSymptoms": ['Disorientation regarding time or place', 'Headache', 'Joint pain', 'Muscle pain', 'Muscle weakness', 'Pain in the limbs', 'Sensitivity to glare', 'Sensitivity to noise', 'Sleeplessness', 'Tiredness'],
      "ProfName": "Chronic fatigue syndrome",
      "Synonyms": null,
      "TreatmentDescription": "Chronic fatigue syndrome can only be diagnosed after all other possible diseases, which the symptoms might explain, have been eliminated via a medical examination. There is no direct treatment for chronic fatigue syndrome, although behavioral therapy may help to alleviate symptoms."
    },
    {
      "Description": "People suffering from mania are under the impression of being unrestrictedly strong and able to do everything they plan. They are in an exhilarated mood, laugh often, even in inappropriate situations and often talk continuously.",
      "DescriptionShort": "Mania is a psychological condition that shows in enhanced, mostly euphoric moods in inappropriate situations. Contrary to persons suffering from depression, patients with a mania find it very difficult to keep calm.",
      "MedicalCondition": "Manic people are distracted easily, they can’t concentrate at all or only for a short period of time and, as mentioned above, talk very fast more or less continuously and often to themselves, they “gabble along”. Sometimes patients show symptoms that are equivalent to delusions; they overestimate themselves, can’t recognise interrelationships anymore or draw the wrong conclusions.",
      "Name": "Mental illness with euphoria and hyperactivity",
      "PossibleSymptoms": ['Aggressiveness', 'Agitation', 'Difficulty to concentrate', 'Increased drive', 'Mood swings', 'Sleeplessness'],
      "ProfName": "Mania",
      "Synonyms": null,
      "TreatmentDescription": "Because of the common combination of delusions and self-overestimation, manic persons are usually only partly criminally liable and not legally competent. In most cases the acute-phase requires a compulsory hospitalization to protect others, but mainly the patients themselves, and to begin treatment. Beginning a therapy during the acute-phase is difficult, as the patients often lack any understanding of the disease. However, it can be treated with various medication, psychotherapy and ergo therapy."
    },
    {
      "Description": "After undergoing through a traumatic experience, weeks or months may be required until the signs of post-traumatic stress disorder show up. The symptoms could be re-experiencing the traumatic moment, avoidance behaviors, and being easily frightened. Patients often suffer from depression, anxiety disorders, or substance abuse.",
      "DescriptionShort": "Post-traumatic stress disorder (PTSD) is a condition that arises as a psycological reaction to a traumatic event. Stress, repeated moments of fear, avoidance of certain situations, and increased fear result from PTSD.",
      "MedicalCondition": "In about 10% of all people who experience trauma develop PTSD and 8% of all people will at one point in their lives, especially victims of rape, torture, and war experiences. Patients relive the trauma again and again and suffer from stressful memories and nightmares. Besides that, patients also avoid confrontations with situations or locations that remind them of the trauma, which in extreme cases can cause patients to withdraw themselves from social circles. Patients furthermore report an increase in their ability to be frightened as well as sleeping and concentration disorders.",
      "Name": "Stress disorder after trauma",
      "PossibleSymptoms": ['Aggressiveness', 'Anxiety', 'Bold area among hair on the head', 'Hair loss', 'Joylessness', 'Mood swings', 'Nervousness', 'Reduced appetite', 'Sleeplessness'],
      "ProfName": "Post-traumatic stress disorder",
      "Synonyms": null,
      "TreatmentDescription": "Post-traumatic stress disorder is treated primarily with psychotherapy, where fear-management strategies and confrontation with fear-triggering environments is discussed. Antidepressant medications may also be employed in conjunction with therapy."
    },
    {
      "Description": "Sleeping disorders describe a state in which the affected person exhibits unhealthy sleep patterns. These include sleeplessness (when falling asleep or trying to stay asleep) or overwhelming drowsiness, sleep-related trouble of breathing (like sleep apnea, associated with snoring and temporary cessation of breathing) or movement (such as “restless leg syndrome”), as well as changes in sleep and similar complaints.",
      "DescriptionShort": "A sleep disorder, known also as somnipathy, is a condition in which the sleep is disturbed. This condition can be serious and interfere with regular emotional, mental, physical, and social functioning. When the person finds it hard to sleep or cannot stay asleep for a long moment without clear cause, the disorder is called insomnia.",
      "MedicalCondition": "Sleeping disorders are very common. Because they can occur on their own or together with other illnesses, it is recommended that the affected person sees a doctor to discover the cause. The following sleep hygiene has negative influence on sleep: light, noise, rich foods before bedtime, consuming alcohol or coffee, smoking, psychological and physical stress, work shifts or irregular working times.",
      "Name": "Sleeping disorder",
      "PossibleSymptoms": ['Agitation', 'Difficulty to concentrate', 'Headache', 'Nervousness', 'Reduced appetite', 'Sleepiness with spontaneous falling asleep', 'Sleeplessness', 'Tiredness', 'Weight gain'],
      "ProfName": "Somnipathy",
      "Synonyms": null,
      "TreatmentDescription": "Lack of sleep can have devastating results, for example, traffic accidents, losing one’s job, or psychological problems. Treatment usually involves the reestablishment of sleep hygiene, in other words, taking measures to promote healthy sleep patterns. If these measures show no clear improvement in quality of sleep, sleep-inducing drugs are an option, though this may lead to dependence. Plant extracts, such as valerian, hops, or lavender may be more suitable."
    },
    {
      "Description": "An acute stress response is a reaction to a stressful event. The response usually comes and disappears quickly (two to three days). However, it can also lead to further damage of the body either mentally or physically.",
      "DescriptionShort": "An acute stress response is a reaction that occurs during or after facing a stressful event. The reaction begins immediately (few minutes) after a severely stressful event. The response can be either mild or severe. It often disappears quickly after the stressful event is gone. If the symptoms are mild, they require no treatment. In more severe cases treatments include behavioural therapy, professional counselling and medication.",
      "MedicalCondition": "An acute stress response can happen immediately after experiencing an extraordinary stressful event, for example traumatic accidents, a war, a disaster, violence, sexual harassment and loss of family member. An acute stress response starts few minutes after such an event and lasts mostly for only two to three days, maximally for four weeks. Conditions that last for a longer period are either classified as posttraumatic stress disorder or as adjustment disorder. Generally speaking, acute stress responses include psychogenic symptoms such as unstable emotions, anxiety, negligence, irritability and the feeling of numbness. People with the problem avoid everything that can trigger the memory of the stressful event. Furthermore also physical symptoms such as rapid heartbeats, sweating, flush or headache can occur. Feared are serious consequences such as social withdrawal and suicidal tendency.",
      "Name": "Shock",
      "PossibleSymptoms":['Anxiety', 'Blackening of vision', 'Feeling faint', 'Nervousness', 'Sleeplessness', 'Tiredness'],
      "ProfName": "Acute stress disorder",
      "Synonyms": "Psychological shock,Mental shock",
      "TreatmentDescription": "If an acute stress response disappears after the stressful event and is not recurrent, then a treatment is normally not necessary. However, it is important to understand the causes of an acute stress response. Talking things over with family and friends may help to improve the situation. For severe cases, it is always recommended to take professional treatments into consideration such as cognitive behavioral therapy, professional counseling and supportive medications."
    },
    {
      "Description": "Eating disorders are a group of psychiatric problems, which manifest in harmful dietary habits. An eating disorder involves eating both too much or too little, abnormal eating habits, and other psychical symptoms.",
      "DescriptionShort": "An eating disorder is an often seen and serious psychiatric problem. It causes the person to have either too much or too little intake of food. It occurs more often with women. Whenever there is any sign of an eating disorder, it is important to consult a psychiatrist before severe consequences occur.",
      "MedicalCondition": "An eating disorder often begins in the presence of abnormal dietary habits. It is more likely to occur in women than in men. There are three main groups of eating disorders. The first one is anorexia nervosa: This is a condition when people, who have a critically low BMI (body mass index), deliberately do not want to take enough food. People with anorexia nervosa have a so called disturbance of body image, which means they feel fat although they actually may be too thin. A problem in patients with anorexia nervosa is the lack of insight for this illness. The second type of eating disorder is bulimia nervosa. This condition makes people, who generally eat few, suffer from massive attacks of food craving that will make them eat unusually large amounts of food. After the excessive intake of food, they may feel guilty and will try to lose the calories. Common methods are self-induced vomiting, laxatives and excessive sport. This behavior is called purging. Persons with bulimia may have normal body weight. The third type of eating disorder is called binge eating: This is a condition when people are tending to have attacks with out-of-control eating. Affected persons feel unable to control the urge to eat and may not even realize their behavior. People with binge eating disorders often have the problem of obesity.",
      "Name": "Eating disorder",
      "PossibleSymptoms": ['Agitation', 'Anxiety', 'Bloated feeling in the stomach', 'Bold area among hair on the head', 'Brittleness of nails', 'Changes in the nails', 'Cravings', 'Difficulty to concentrate', 'Distended abdomen', 'Dizziness', 'Dry skin', 'Feeling faint', 'Flatulence', 'Hair loss', 'Increased appetite', 'Joylessness', 'Missed period', 'Mood swings', 'Nausea', 'Nervousness', 'Overweight', 'Sadness', 'Sensitivity to cold', 'Tiredness', 'Underweight', 'Vomiting', 'Weight gain', 'Weight loss'],
      "ProfName": "Psychogenic eating disorders",
      "Synonyms": null,
      "TreatmentDescription": "The treatments for an eating disorder include the education of a healthy diet and nutrition, and avoidance of improper behavior such as purging. In the foreground is talk therapy. Additionally, especially for patients with bulimia, medication such as anti-depressants may be prescribed. In severe cases, such as patients with anorexia nervosa and a critical body mass index, it is necessary to be hospitalized to improve nutrition and to determine the nature of the psychiatric problems."
    },
    {
      "Description": "The condition \"tourette's syndrome\" was named after the revolutionary French neurologist, Dr. Georges Gilles de la Tourette, who was the first to describe the disorder in 1885. The initial symptoms of the condition are noticed typically in childhood, between three and nine years old. Gilles de la Tourette syndrome can happen in all people, no matter their ethnic groups. Men are affected more than women. In many cases, the patient shows less or symptoms of milder complexity like vocal tics or chronic motoric disturbances. Even if the disorder can be chronic with symptoms present during the entire life, the tic symptoms become worst for most patients in the beginning of their teen years. The symptoms improve at the end of their teen years but continue into their adulthood.",
      "DescriptionShort": "Tourette’s syndrome is a neuro-psychological disorder that results from a faulty development of the central nervous system. People with the syndrome suffer from so called tics, which are unwanted repetitive movements (motor tics) or sounds (vocal tics). The syndrome usually starts from childhood. It is recommended to visit a neurologist if there is any related symptom.",
      "MedicalCondition": "The exact cause of Tourette’s syndrome is somehow not clear at the moment. However, it is thought to be associated with a genetic problem that leads to an undesirable development of the motoric regulatory system in the brain. This genetic problem, which promotes the occurrence of tic disorders, can be inherited. As a result, there are aberrations in the brain of affected people leading to an overstimulation of motoric regulatory loops with the neurotransmitter dopamine, which then results in the execution of improper behaviors. Generally speaking, Tourette’s syndrome often starts from childhood, and happens to males more often than females. People with the syndrome will perform some repetitive and uncontrolled movements and sounds, which are called motor tics and vocal tics in medical terms. Blurting out some rude words or gestures unintentionally is just one of many forms of complex tics, which affects about 30% of the patients.",
      "Name": "Tourette's syndrome",
      "PossibleSymptoms": ['Eye blinking', 'Tic'],
      "ProfName": "Gilles de la Tourette syndrome",
      "Synonyms": null,
      "TreatmentDescription": "Tourette’s syndrome can neither be cured nor treated causatively. However, medication can still help to control the tic disorders. Frequently prescribed medications are psychiatric drugs such as neuroleptics, anticonvulsants or antidepressants, which all influence the neurotransmitters and therefore help to improve the symptoms. Besides medications, behavioral therapy and psychotherapy may help patients to live with the disease and to learn techniques to suppress their tics."
    },
    {
      "Description": "Narcolepsy is a chronic neurological disorder belonging to the group of hypersomnia. It leads to an inability of the brain to regulate the sleep-wake cycles well. People with narcolepsy may have problems like excessive daytime sleepiness, sleep paralysis, hypnagogic hallucinations and cataplexy. The excessive daytime sleepiness can result in sudden sleep attacks, which may last from some seconds to minutes, even when persons had enough sleep during night. Narcolepsy can occur at any age.",
      "DescriptionShort": "Narcolepsy describes a chronic neurological disorder leading to an inability of the brain to regulate sleep-wake cycles. The cause of narcolepsy is not well known. It is recommended to consult a neurologist, if respective symptoms appear.",
      "MedicalCondition": "The exact cause of narcolepsy is unknown. Some researches show that narcolepsy may be related to low levels of hypocretin (orexin), which is neurotransmitter in the brain. This may be the reason for the deregulation of the sleep-wake cycles. The low concentration of hypocretin is thought to be associated with a loss of brain cells that produce hypocretin due to some autoimmune reactions. Whether other factors such as vaccinations, a trauma or injury to the brain, tumors in the brain, stress, an irregular sleep schedule, and abuse of medications or any other damage to the brain can result in narcolepsy, is not finally proven. The common symptoms include extreme daytime sleepiness (sleep attacks despite sufficient amount of sleep), cataplexy (sudden loss of muscle tone while retaining consciousness, triggered by a emotional stimulus such as joy or fright), hypnagogic hallucinations (hallucinations directly after awakening), as well as sleep paralysis (inability to move directly after awakening while fully conscious).",
      "Name": "Extreme tendency to fall asleep",
      "PossibleSymptoms": ['Drowsiness', 'Hallucination', 'Muscular weakness in the arm', 'Muscular weakness in the leg', 'Sleepiness with spontaneous falling asleep', 'Tiredness'],
      "ProfName": "Narcolepsy",
      "Synonyms": null,
      "TreatmentDescription": "Lifestyle changes, called sleep hygiene, can help to reduce the symptoms of narcolepsy, for example: 1) a regular sleep schedule, 2) keeping the bedroom dark during sleep, 3) avoiding caffeine and alcohol before bedtime, 4) not smoking, 5) doing something relaxing to fall asleep before bedtime, 6) regular exercise. Individually assessed strategies like daily sleeping episodes or the avoidance of certain situations will help to handle the disease. In addition, medications might be used for the treatment of narcolepsy, for example, 1) stimulant medicines, such as methylphenidate or modafenil, can help to stay awake during the day, 2) antidepressant medicines can help to reduce cataplexy, sleep paralysis and even hallucinations, 3) sodium oxybate can also help to control day time sleepiness and cataplexy. It is recommended to visit a neurologist if there are any respective symptoms."
    },
    {
      "Description": "An obsessive-compulsive disorder is a psychiatric disorder, which leads the affected persons to have uncontrollable obsessive thoughts or to perform compulsive acts. The symptoms are separated in obsessive thoughts and obsessive acts. Obsessive-compulsive disorders often co-occur with anxiety disorders or depressions.",
      "DescriptionShort": "An obsessive-compulsive disorder is a psychiatric disorder leading to obsessive thoughts or compulsive acts in affected persons. People with the disorder should consult a psychiatrist for a proper treatment in order to control the symptoms. The treatments often include medications and behavioral therapy.",
      "MedicalCondition": "The cause of an obsessive-compulsive disorder is still unknown. There are several psychological and biological explanatory models. Well known is that obsessive-compulsive disorders are associated with anxiety disorders, depressions and other psychiatric diseases. The symptoms of an obsessive-compulsive disorder are divided in obsessive thoughts and compulsive acts. An obsessive thought can be any repeatedly imposed thought that is recognized as unreasonable by the patient. These thoughts typically include topics such as aggression and violence, pollution, orderliness, religion or sexuality. Compulsive acts refer to over-repetitive behaviors such as washing, checking, counting, or vocalize words. A compulsive act is the result of a compulsive impulse, a strong craving for an activity that only diminishes after performing the respective action.",
      "Name": "Obsessive-compulsive disorder",
      "PossibleSymptoms": ['Agitation', 'Anxiety', 'Eye blinking', 'Mood swings', 'Tic'],
      "ProfName": "Obsessive-compulsive personality disorder",
      "Synonyms": "OCD",
      "TreatmentDescription": "The treatments of an obsessive-compulsive disorder often include medications and behavioral therapy. Antidepressants are often used to increase the amount of serotonin and therefore to reduce depression, anxiety or compulsive symptoms. In severe cases neuroleptics can be prescribed. Besides, a behavioral therapy can help people to face situations, which normally trigger the disorder, without displaying any symptoms. Under the triggering situation, people with an obsessive-compulsive disorder are encouraged to deal with the stress of compulsive impulses and avoid meaningless behavior."
    },
    {
      "Description": "Delirium is a disorder of the mental status. It often occurs quickly, has a fluctuating course of symptoms and has specific causes. Delirium can make people feel confused about other people, time and location. It makes people unable to pay attention or think clearly. Furthermore, it can lead to impaired consciousness and, in severe cases, a comatose state.",
      "DescriptionShort": "Delirium is a disorder of the mental status of a person. Delirium usually starts suddenly and has a changing course of symptoms. It is often triggered by a specific cause and requires immediate medical treatment. It is possible to cure delirium if the trigger is identified and treated.",
      "MedicalCondition": "There are various causes of delirium. They include abuse or misuse of medications, infections, severe pain, being isolated for a long period, malnutrition, high fever, damage to the brain, impaired metabolism and electrolyte balance, postoperatively, drugs, hypoxia or cardiac disease. A common delirium is alcohol withdrawal delirium. Delirium often occurs within a short time frame and may last for quite a while. The most common sign of delirium is confusion. People with delirium cannot recognize the people around them; lose sense of time and location. It may also lead to changes of behavior, emotional confusion, loss of focus and furthermore the sudden loss of consciousness.",
      "Name": "Confusional state",
      "PossibleSymptoms": ['Absence of a pulse', 'Aggressiveness', 'Agitation', 'Anxiety', 'Difficulty in speaking', 'Difficulty to concentrate', 'Disorientation regarding time or place', 'Forgetfulness', 'Hallucination', 'Irregular heartbeat', 'Memory gap', 'Mood swings', 'Nervousness', 'Sleeplessness', 'Trouble understanding speech'],
      "ProfName": "Delirium",
      "Synonyms": "Acute confusional state",
      "TreatmentDescription": "Treatment for delirium depends on the type of trigger. Patient may need to stay at the hospital for a complete work-up and treatment of the underlying cause. Delirium is curable and reversible as long as an early diagnosis and treatment are put in to place. In some cases it may be a life-threatening emergency and may be fatal."
    },
    {
      "Description": "Alcohol consumption is a type of social behavior in many cultures. People may drink to socialize, celebrate, and relax. Drinking alcohol moderately is not a problem, but drinking too much will increase the risks of a variety of diseases. Especially problematic is the feature of alcohol consumption to lead to an addiction.",
      "DescriptionShort": "Moderate alcohol consumption itself is not a problem, but alcohol can cause a series of health problems when drinking too much. Frequent alcohol consumption potentially leads to an addiction. Alcohol overuse can prevent our normal body function and damage organs. If someone is abusing alcohol, it is highly advised to consult a specialist.",
      "MedicalCondition": "Overusing alcohol can damage a variety of human organs. The WHO defines harmful alcohol consumption as intake of more than 60g pure alcohol per day for men and 40g per day for women. The organs that may take damage are: 1) brain: alcohol interferes with the brain’s communication pathways, and can affect human mood and behavior. Besides chronic high alcohol intake can lead to permanent brain damage. 2) heart: arrhythmia, cardiomyopathy, stroke and high blood pressure, 3) liver: fatty liver, alcoholic hepatitis, fibrosis and cirrhosis, 4) pancreas: alcohol can make the pancreas produce toxic substances that lead to pancreatitis, 5) cancer: it can increase the risks of mouth, esophagus, liver, throat and breast cancers, 6) immune system: drinking too much can also weaken the human immune system. Symptoms of intoxication with alcohol and consequences of drinking too much include: 1) reduced inhibition and aggression, 2) slurred speech, 3) motor impairment, 4) confusion, 5) memory and concentration problems, 6) coma, 7) breathing problems, and even 8) death. Alcohol addiction is not defined by an amount of alcohol consumed but by psychic symptoms such as craving, loss of control of the amount consumed, withdrawal symptoms and social consequences.",
      "Name": "Alcohol consumption",
      "PossibleSymptoms": ['Aggressiveness', 'Agitation', 'Anxiety', 'Blackening of vision', 'Cramps', 'Deepened breathing', 'Diarrhea', 'Difficulty in finding words', 'Difficulty in speaking', 'Difficulty to concentrate', 'Difficulty with gait', 'Disorientation regarding time or place', 'Fast', 'Feeling faint', 'Forgetfulness', 'Hallucination', 'Impaired balance', 'Impairment of male potency', 'Night sweats', 'Numbness in the arm', 'Numbness in the leg', 'Problems with the sense of touch in the feet', 'Sadness', 'Skin redness', 'Sweating', 'Tingling', 'Tremor at rest', 'Tremor on movement', 'Trouble understanding speech', 'Vomiting'],
      "ProfName": "Excessive alcohol consumption",
      "Synonyms": null,
      "TreatmentDescription": "An acute intoxication with alcohol may be life threatening and, in case of complete loss of consciousness, needs immediate intensive care in order to maintain vital functions such as breathing and circulation. Intoxicated persons should be put in a recovery position to protect them from aspiration of vomit. One of the most well-known treatments for alcohol use disorder is to join the mutual support group Alcoholics Anonymous. Besides, there are plenty of other possibilities like support with medication and behavioral therapies, as well as combinations of treatments."
    },
    {
      "Description": "When people use caffeine regularly, their bodies will get used to it. If they stop caffeine intake or do not take it as normal, the change will be accompanied by some symptoms like headache, sleeping disorders or restlessness. This is called caffeine withdrawal.",
      "DescriptionShort": "People who normally have a regular caffeine intake but then suddenly stop will probably have caffeine withdrawal. It often causes symptoms which make people uncomfortable, so it is better to slowly reduce the usage of caffeine than suddenly quitting it completely. If necessary, medication will be used to stop withdrawal symptoms.",
      "MedicalCondition": "Caffeine occurs naturally in plants like coffee beans, tea, kola nuts and the like. It is often used to flavor drinks or food. When people keep eating or drinking these kinds of food or drinks for more than 3 days and then suddenly stop, caffeine withdrawal will probably occur within 6-24 hours, and the symptoms might last for 2-9 days. Caffeine withdrawal could cause side effects like 1)  a headache which usually starts behind the eyes and then to the front of the head, 2) sleepiness, 3) irritability, 4) lethargy and lack of motivation, 5) constipation, 6) depression, 7) muscle pain and stiffness , 8) lack of concentration, 9) flu-like symptoms and 10) insomnia.  In general, the more caffeine was consumed, the more severe the withdrawal symptoms are likely to be.",
      "Name": "Caffeine withdrawal",
      "PossibleSymptoms": ['Agitation', 'Headache', 'Tiredness'],
      "ProfName": "Caffeine dependence",
      "Synonyms": null,
      "TreatmentDescription": "There are some principals for the treatment of caffeine withdrawal: 1) decrease the intake of caffeine gradually and increase the intake of water, 2) choose low caffeine products as a substitute, 3) take a rest or massage when symptoms occur and 4) if necessary, take non-steroidal analgesics according to a doctor’s order."
    },
    {
      "Description": "Psychogenic issues describe any problem or disorder of mental health. A psychogenic problem may affect the mood, behavior and thoughts of an individual. Psychogenic problems may also result in psychogenic illness such as depression, anxiety, behavioral disorders, mania and schizophrenia.",
      "DescriptionShort": "Psychogenic issues may be any mental problems that could affect daily life and normal functions. It is recommended to consult a specialist if any psychogenic problems occur. Treatment often includes psychotherapy or specific medication. ",
      "MedicalCondition": "There may be various causes of psychogenic problems; for example, hereditary, life styles and experiences, stress, drug abuse and physical or mental trauma. People with a psychogenic problem may experience symptoms such as feeling sad, confusion, fear, anger, worries, tiredness or dramatic changes of emotions. All these emotions are stronger or last longer than they would normally occur. Furthermore, some people may try to avoid socializing and cannot deal with stress or other problems. A psychogenic problem may even turn into a physical problem. Common examples include stomach pain, headache, and diarrhea, vomiting and sleeping disorders. A psychogenic problem may progress and develop into a psychogenic illness such as depression, anxiety disorder, behavior disorder, mania or schizophrenia.",
      "Name": "Psychogenic issues",
      "PossibleSymptoms":['Aggressiveness', 'Agitation', 'Difficulty in speaking', 'Hallucination', 'Mood swings', 'Physical inactivity', 'Sadness'],
      "ProfName": "Psychogenic disorder",
      "Synonyms": null,
      "TreatmentDescription": "The treatment of psychogenic problems consists of a combination of consultation with doctor, psychotherapy and use of specific medications. In most cases, early symptoms may be kept under control with the appropriate treatment. It is strongly recommended to consult a specialist to avoid development of psychogenic illnesses when there are any psychogenic problems."
    },
    {
      "Description": "Poor sleep hygiene describes any bad habits before sleep, which may affect the quality of sleep. People with poor sleep hygiene may have irregular sleep schedules, difficulty falling asleep, and often wake up during the night and have trouble falling asleep again.",
      "DescriptionShort": "Poor sleep hygiene is a term used for any behavior that can disturb people’s normal sleep, and it can therefore also affect people’s normal functioning during daytime. It is important to change the behavior or habit that can disrupt normal sleep.",
      "MedicalCondition": "Sleep hygiene is the practice that assists people in having good quality sleep and as a result experience high levels of energy during the day. Hygiene here refers to habits that can affect the sleep. For example, what time do people go to sleep, where do people sleep, and what do people do before sleep. Generally speaking, poor sleep hygiene is defined as bad habits that make sleeping difficult or unsuccessful. People with poor sleep hygiene may have symptoms such as difficulty in falling asleep or sleeping through the night, inability to stay alert during daytime or daytime sleepiness. Examples of poor sleep hygiene include irregular times for going to bed or waking up, intake of alcohol, caffeine, nicotine, drugs that can interrupt sleep, too much work before sleep, overstimulation with late-night activities such as sports, using the computer or watching television, a poor sleep environment (temperature, light, sounds) and any other inappropriate behavior before sleep including late-night snacks.",
      "Name": "Bad sleeping habits",
      "PossibleSymptoms": ['Agitation', 'Mood swings', 'Morning stiffness', 'Neck pain', 'Neck stiffness', 'Nervousness', 'Sleepiness with spontaneous falling asleep', 'Sleeplessness'],
      "ProfName": "Poor sleep hygiene",
      "Synonyms": null,
      "TreatmentDescription": "In order to have good sleep hygiene, it is important to change certain behaviors and habits that can affect normal sleep. Here are some suggestions for having good sleep hygiene: 1) avoid daytime sleep and overlong sleep time, 2) arrange a regular sleep schedule, 3) avoid intake of alcohol, caffeine, nicotine and food before sleep, 4) exercise regularly during the daytime and not after 6pm, 5) have enough exposure to sunlight, and 6) ensure a good sleep environment (good temperature, no lights and no sounds)."
    },
    {
      "Description": "Stress can be any condition that makes people feel tense, angry, nervous, anxious or insecure. It is a physiological reaction of the human body when facing certain changes, threats and fears. A stress reaction is supposed to enable a person to manage extraordinary situations. But chronic stress may result in either physical or mental symptoms that could seriously affect daily living.",
      "DescriptionShort": "Stress is the body’s reaction to extraordinary situations that may cause change, threat, or fear. Stress results in both physical and mental symptoms. If the symptoms of stress start to affect daily life, it is recommended to consult a psychiatrist or a psychologist.",
      "MedicalCondition": "Stress is a common condition that most people experience at some point in their lives. But there are two types of stress with different meanings: 1) Eustress describes the positive stress, which encourages people to achieve more than usual. It may lead to a feeling of satisfaction. 2) Distress describes the negative stress that is felt to be threatening or overstraining. This sort of stress can be produced by seriously dangerous situations like an accident, war or a natural disaster. But also less disastrous situations, like problems in the job or family, can lead to distress, when there is no compensation for stress or when a person feels helpless and does not know a way to handle with it. When a stress response is triggered, a series of changes will occur within the human body. For example: 1) a rise in pulse rate, 2) redirection of blood away from the extremities and to the major organs, and 3) release of cortisone, adrenalin and noradrenalin, which may cause physical and mental short and long term changes. However, the symptoms caused by stress will differ from person to person. Some people will feel physical symptoms such as headache, pain, diarrhea, constipation, nausea or dizziness. And some may have mental symptoms such as depression, anxiety, and loss of sexual drive. Chronic distress may lead to a so called burnout-syndrome.",
      "Name": "State of stress",
      "PossibleSymptoms": ['Anxiety', 'Bold area among hair on the head', 'Difficulty to concentrate', 'Forgetfulness', 'Hair loss', 'Headache', 'Increased appetite', 'Itching of skin', 'Neck pain', 'Nervousness', 'Reduced appetite', 'Sleeplessness', 'Weight gain', 'Weight loss'],
      "ProfName": "Stress",
      "Synonyms": "Stress state",
      "TreatmentDescription": "Strategies for stress relief (coping) will differ from person to person, but making certain lifestyle changes will be a good start. Here are some suggestions: 1) have a well-balanced, healthy diet, 2) enough sleep and exercise, 3) limit caffeine and alcohol intake, 4) avoid drug abuse, 5) find a way to relax, 6) regular rest time and 7) spend time with family and friends. If the symptoms do not improve, it is highly recommended to consult a psychiatrist or a psychologist."
    }
  ]




