export const _cols = [
    "Disorder",
    "Share of global population with disorder (2017) [difference across countries]",
    "Number of people with the disorder (2017)",
    "Share of males:females with disorder"
]

export const _rows = [
    {
        "disorder" : "Any mental health disorder",
        "percentage" : "10.7%",
        "number" : "792 million",
        "malePercentage" : "9.3% males",
        "femalePercentage" : "11.9% females",
    },
    {
        "disorder" : "Depression",
        "percentage" : "3.4%",
        "countryDifference" : "[2-6%]",
        "number" : "264 million",
        "malePercentage" : "2.7% males",
        "femalePercentage" : "4.1% females",
        "link" : "https://ourworldindata.org/grapher/share-with-depression"
    },
    {
        "disorder" : "Anxiety disorders",
        "percentage" : "3.8%",
        "countryDifference" : "[2.5-7%]",
        "number" : "284 million",
        "malePercentage" : "2.8% males",
        "femalePercentage" : "4.7% females",
        "link" : "https://ourworldindata.org/grapher/share-with-anxiety-disorders",
    },
    {
        "disorder" : "Bipolar disorders",
        "percentage" : "0.6%",
        "countryDifference" : "[0.3-1.2%]",
        "number" : "46 million",
        "malePercentage" : "0.55% males",
        "femalePercentage" : "0.65% females",
        "link" : "https://ourworldindata.org/grapher/share-with-bipolar-disorder",
    },
    {
        "disorder" : "Eating disorders",
        "percentage" : "0.2%",
        "countryDifference" : "[0.1-1%]",
        "number" : "16 million",
        "malePercentage" : "0.13% males",
        "femalePercentage" : "0.29% females",
        "link" : "https://ourworldindata.org/grapher/share-with-an-eating-disorder",
    },
    {
        "disorder" : "Schizophrenia",
        "percentage" : "0.3%",
        "countryDifference" : "[0.2-0.4%]",
        "number" : "20 million",
        "malePercentage" : "0.26% males",
        "femalePercentage" : "0.25% females",
        "link" : "https://ourworldindata.org/grapher/share-of-population-with-schizophrenia",
    },
    {
        "disorder" : "Any mental or substance use disorder",
        "percentage" : "13%",
        "countryDifference" : "[11-18%]",
        "number" : "970 million",
        "malePercentage" : "12.6% males",
        "femalePercentage" : "13.3% females",
        "link" : "https://ourworldindata.org/grapher/share-with-mental-and-substance-disorders",
    },
    {
        "disorder" : "Alcohol use disorder",
        "percentage" : "14%",
        "countryDifference" : "[0.5-5%]",
        "number" : "107 million",
        "malePercentage" : "2% males",
        "femalePercentage" : "0.8% females",
        "link" : "https://ourworldindata.org/grapher/share-with-alcohol-use-disorders",
    },
    {
        "disorder" : "Drug use disorder (excluding alcohol)",
        "percentage" : "0.9%",
        "countryDifference" : "[0.4-3.5%]",
        "number" : "71 million",
        "malePercentage" : "1.3% males",
        "femalePercentage" : "0.6% females",
        "link" : "https://ourworldindata.org/grapher/share-with-drug-use-disorders",
    },
]
